<?php

namespace TestBundle\Entity;
use Doctrine\ORM\UnitOfWork;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function remove($id)
    {
        $conn = $this->_em->getConnection();
        $sql = 'DELETE FROM Game WHERE id = :id;';
        $statement = $conn->executeQuery($sql, array('id' => $id));
        $game = $this->_em->getReference('TestBundle:Game', $id);
        $result = $statement->rowCount();

        return $result;

    }

    public function clearAllGames()
    {
        $conn = $this->_em->getConnection();
        $sql = 'DELETE FROM Game;';
        $statement = $conn->executeQuery($sql);
        $result = $statement->rowCount();

        return $result;

    }
}
